### ISSUE TITLE
Failed to fetch metadata for icons

### ISSUE THREAD

**Issue by pizofreude** [HR/github-clone#12] opened 2022-12-20 10:10 UTC
Hi,
I'm trying to clone a subdirectory as linked below via ghclone command:
https://github.com/all-contributors/all-contributors/tree/master/website/static/img/icons

This is the command I gave in git bash inside my local git repo project directory:
MINGW64 ~src/site/images/icons
$ ghclone https://github.com/all-contributors/all-contributors/tree/master/website/static/img/icons
Cloning into 'icons'...
Failed to fetch metadata for icons

I'm using windows 10 with Python 3.11. This is the installed directory of ghclone in my machine:
C:\Windows\system32>pip install github-clone
Requirement already satisfied: github-clone in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (1.2.0)
Requirement already satisfied: requests>=2.20.0 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from github-clone) (2.28.1)
Requirement already satisfied: docopt>=0.6.2 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from github-clone) (0.6.2)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20.0->github-clone) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20.0->github-clone) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20.0->github-clone) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abdul\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.20.0->github-clone) (2022.12.7)

Can you please help? I cannot figure out what I'm missing.
Thanks in advance for your assistance.

**Comment by HR** [comment] 2023-02-13 14:31
Duplicate of https://github.com/HR/github-clone/issues/9

**Closed as completed by HR** 2023-02-13 14:31 UTC
